# EEG data from basic sensory task in Schizophrenia

Authors: Karl Jääts, Mihkel Kruusi, Siim K. Koger

In [84]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib notebook

In [85]:
demo = pd.read_csv("../data/demographic.csv")
erp_data = pd.read_csv("../data/ERPdata.csv")
display(erp_data[:4])

,subject,condition,Fz,FCz,Cz,FC3,FC4,C3,C4,CP3,CP4,time_ms
0,1,1,5.533701,5.726507,5.469535,5.386723,4.588875,6.560092,4.542811,5.397492,5.103695,-1500.0000
1,1,1,5.651489,5.837326,5.773131,5.627975,4.822217,6.739976,4.811770,5.541357,5.379273,-1499.0234
2,1,1,5.717580,5.932924,5.948466,5.826460,4.979647,7.026199,5.053779,5.634972,5.600504,-1498.0469
3,1,1,5.703267,5.968103,5.851512,5.812192,4.992899,6.940671,5.106650,5.543577,5.589775,-1497.0703

### Baseline correction

In [86]:
BL = erp_data[(erp_data.time_ms >= -100) & (erp_data.time_ms <= 0)].groupby(['subject', 'condition']).mean()

N1amps = erp_data[(erp_data.time_ms >= 80) & (erp_data.time_ms <= 100)].groupby(['subject', 'condition']).mean()

P2amps = erp_data[(erp_data.time_ms >= 150) & (erp_data.time_ms <= 190)].groupby(['subject', 'condition']).mean()

display(BL[:4])
display(N1amps[:4])
N1amps[["Fz", "FCz", "Cz"]] = N1amps[["Fz", "FCz", "Cz"]] - BL[["Fz", "FCz", "Cz"]]
display(N1amps[:4])

P2amps[["Fz", "FCz", "Cz"]] = P2amps[["Fz", "FCz", "Cz"]] - BL[["Fz", "FCz", "Cz"]]

                         Fz       FCz        Cz       FC3       FC4        C3  \
subject condition
1       1          0.008189  0.009720  0.016123  0.010271  0.008870  0.020370
        2         -0.006360 -0.005304 -0.003952 -0.003845 -0.006621 -0.001391
        3         -0.010922 -0.010625 -0.005603 -0.013810 -0.009102 -0.004477
2       1          0.003162  0.001844  0.004312  0.002926  0.001148  0.005238

                         C4       CP3       CP4    time_ms
subject condition
1       1          0.011190  0.018696  0.012184 -49.804694
        2         -0.002625 -0.005219 -0.001973 -49.804694
        3         -0.003762  0.001899  0.000354 -49.804694
2       1          0.004516  0.005816  0.004715 -49.804694

                         Fz       FCz        Cz       FC3       FC4        C3  \
subject condition
1       1         -3.969841 -3.531790 -2.742199 -2.411903 -4.154254 -1.621322
        2         -8.308424 -8.990923 -9.474523 -8.171511 -8.710126 -8.271828
        3          0.967277  1.329361  1.825440  1.013117  1.553381  1.351172
2       1         -2.852217 -2.915010 -2.492622 -1.702627 -2.906801 -1.227084

                         C4       CP3       CP4    time_ms
subject condition
1       1         -3.716837 -2.547987 -3.497883  89.843757
        2         -8.220033 -8.231913 -8.064169  89.843757
        3          1.075092  1.737629  0.796994  89.843757
2       1         -2.110256 -0.918345 -1.365077  89.843757

                         Fz       FCz        Cz       FC3       FC4        C3  \
subject condition
1       1         -3.978030 -3.541510 -2.758322 -2.411903 -4.154254 -1.621322
        2         -8.302064 -8.985619 -9.470571 -8.171511 -8.710126 -8.271828
        3          0.978199  1.339986  1.831042  1.013117  1.553381  1.351172
2       1         -2.855379 -2.916854 -2.496934 -1.702627 -2.906801 -1.227084

                         C4       CP3       CP4    time_ms
subject condition
1       1         -3.716837 -2.547987 -3.497883  89.843757
        2         -8.220033 -8.231913 -8.064169  89.843757
        3          1.075092  1.737629  0.796994  89.843757
2       1         -2.110256 -0.918345 -1.365077  89.843757

### Preparing data

In [87]:
# subtract the button press control trial (condition = 3) from the button+tone trial amplitude,
# and then drop the button press control data from the sets
display(N1amps[:3])
N1amps.loc[(slice(None),1), ['Fz', 'FCz', 'Cz']] = N1amps.loc[(slice(None),1), ['Fz', 'FCz', 'Cz']] - N1amps.loc[(slice(None),3), ['Fz', 'FCz', 'Cz']].values
N1amps = N1amps.drop(index=3, level=1)
display(N1amps[:3])

P2amps.loc[(slice(None),1), ['Fz', 'FCz', 'Cz']] = P2amps.loc[(slice(None),1), ['Fz', 'FCz', 'Cz']] - P2amps.loc[(slice(None),3), ['Fz', 'FCz', 'Cz']].values
P2amps = P2amps.drop(index=3, level=1)

                         Fz       FCz        Cz       FC3       FC4        C3  \
subject condition
1       1         -3.978030 -3.541510 -2.758322 -2.411903 -4.154254 -1.621322
        2         -8.302064 -8.985619 -9.470571 -8.171511 -8.710126 -8.271828
        3          0.978199  1.339986  1.831042  1.013117  1.553381  1.351172

                         C4       CP3       CP4    time_ms
subject condition
1       1         -3.716837 -2.547987 -3.497883  89.843757
        2         -8.220033 -8.231913 -8.064169  89.843757
        3          1.075092  1.737629  0.796994  89.843757

                         Fz       FCz        Cz       FC3       FC4        C3  \
subject condition
1       1         -4.956229 -4.881496 -4.589365 -2.411903 -4.154254 -1.621322
        2         -8.302064 -8.985619 -9.470571 -8.171511 -8.710126 -8.271828
2       1         -3.512055 -3.476013 -3.102247 -1.702627 -2.906801 -1.227084

                         C4       CP3       CP4    time_ms
subject condition
1       1         -3.716837 -2.547987 -3.497883  89.843757
        2         -8.220033 -8.231913 -8.064169  89.843757
2       1         -2.110256 -0.918345 -1.365077  89.843757

In [88]:
# convert electrode columns to rows with labels:

N1amps = N1amps.reset_index()
N1amps = pd.melt(N1amps, id_vars=['subject', 'condition'], value_vars=['Fz', 'FCz', 'Cz'])

P2amps = P2amps.reset_index()
P2amps = pd.melt(P2amps, id_vars=['subject', 'condition'], value_vars=['Fz', 'FCz', 'Cz'])

In [132]:
#(3) join with demographics:

N1amps_demo = pd.merge(N1amps, demo, on='subject')
P2amps_demo = pd.merge(P2amps, demo, on='subject')

print('Merged N1amps and demographics: pd.merge(N1amps, demo, on=\'subject\')\n')
display(N1amps_demo[:6])
print('\n\n\n')
print('Merged P2amps and demographics: P2amps_demo = pd.merge(P2amps, demo, on=\'subject\')\n')
display(P2amps_demo[6:12])

Merged N1amps and demographics: pd.merge(N1amps, demo, on='subject')

   subject  condition variable     value   group  gender   age   education
0        1          1       Fz -4.956229       0       M    44        16.0
1        1          2       Fz -8.302064       0       M    44        16.0
2        1          1      FCz -4.881496       0       M    44        16.0
3        1          2      FCz -8.985619       0       M    44        16.0
4        1          1       Cz -4.589365       0       M    44        16.0
5        1          2       Cz -9.470571       0       M    44        16.0

Merged P2amps and demographics: P2amps_demo = pd.merge(P2amps, demo, on='subject')

    subject  condition variable     value   group  gender   age   education
6         2          1       Fz  4.073833       0       M    39        17.0
7         2          2       Fz  0.849951       0       M    39        17.0
8         2          1      FCz  4.362968       0       M    39        17.0
9         2          2      FCz  0.994043       0       M    39        17.0
10        2          1       Cz  4.218022       0       M    39        17.0
11        2          2       Cz  1.242232       0       M    39        17.0

In [135]:
group_map = {0: 'Control', 1: 'Schizo'}
condition_map = {1: 'Button tone', 2: 'Playback'}

#N1amps_demo['group'].map(group_map)
#N1amps_demo['condition'].map(condition_map)

#N1amps_demo['group'].map({'0': 'Control', '1': 'Schizo'})
#N1amps_demo['condition'].map({1: 'Button_tone', 2: 'Playback'})

N1amps_demo_copy = N1amps_demo.copy()

N1amps_demo_copy.condition.replace(to_replace=condition_map, inplace=True)
display(N1amps_demo_copy)
N1amps_demo_copy.group.replace(to_replace=group_map, inplace=True)
display(N1amps_demo_copy)

     subject    condition variable     value   group  gender   age   education
0          1  Button_tone       Fz -4.956229       0       M    44        16.0
1          1     Playback       Fz -8.302064       0       M    44        16.0
2          1  Button_tone      FCz -4.881496       0       M    44        16.0
3          1     Playback      FCz -8.985619       0       M    44        16.0
4          1  Button_tone       Cz -4.589365       0       M    44        16.0
5          1     Playback       Cz -9.470571       0       M    44        16.0
6          2  Button_tone       Fz -3.512055       0       M    39        17.0
7          2     Playback       Fz -5.297909       0       M    39        17.0
8          2  Button_tone      FCz -3.476013       0       M    39        17.0
9          2     Playback      FCz -5.606404       0       M    39        17.0
10         2  Button_tone       Cz -3.102247       0       M    39        17.0
11         2     Playback       Cz -4.964120       0       M    39        17.0
12         3  Button_tone       Fz  0.325926       0       M    53        18.0
13         3     Playback       Fz -5.567956       0       M    53        18.0
14         3  Button_tone      FCz  0.421280       0       M    53        18.0
15         3     Playback      FCz -6.284536       0       M    53        18.0
16         3  Button_tone       Cz  0.787100       0       M    53        18.0
17         3     Playback       Cz -6.029682       0       M    53        18.0
18         4  Button_tone       Fz -4.623123       0       M    52        15.0
19         4     Playback       Fz -7.744804       0       M    52        15.0
20         4  Button_tone      FCz -3.269260       0       M    52        15.0
21         4     Playback      FCz -7.032767       0       M    52        15.0
22         4  Button_tone       Cz -3.870647       0       M    52        15.0
23         4     Playback       Cz -5.576872       0       M    52        15.0
24         5  Button_tone       Fz -4.070241       0       M    41        16.0
25         5     Playback       Fz -5.534389       0       M    41        16.0
26         5  Button_tone      FCz -4.600175       0       M    41        16.0
27         5     Playback      FCz -6.163895       0       M    41        16.0
28         5  Button_tone       Cz -4.194328       0       M    41        16.0
29         5     Playback       Cz -5.780724       0       M    41        16.0
..       ...          ...      ...       ...     ...     ...   ...         ...
456       77  Button_tone       Fz -3.716580       1       M    28        13.0
457       77     Playback       Fz -2.372095       1       M    28        13.0
458       77  Button_tone      FCz -2.978306       1       M    28        13.0
459       77     Playback      FCz -2.959705       1       M    28        13.0
460       77  Button_tone       Cz -1.005001       1       M    28        13.0
461       77     Playback       Cz -0.762281       1       M    28        13.0
462       78  Button_tone       Fz -5.710311       1       F    32        16.0
463       78     Playback       Fz -3.336351       1       F    32        16.0
464       78  Button_tone      FCz -5.767371       1       F    32        16.0
465       78     Playback      FCz -3.097613       1       F    32        16.0
466       78  Button_tone       Cz -5.382087       1       F    32        16.0
467       78     Playback       Cz -3.416490       1       F    32        16.0
468       79  Button_tone       Fz  0.148423       1       M    37        16.0
469       79     Playback       Fz -7.041500       1       M    37        16.0
470       79  Button_tone      FCz  1.920338       1       M    37        16.0
471       79     Playback      FCz -9.497400       1       M    37        16.0
472       79  Button_tone       Cz -1.094268       1       M    37        16.0
473       79     Playback       Cz -8.086755       1       M    37        16.0
474       80  Button_tone       Fz -1.428581       1       M    33        13.0
475       80     Playback       Fz -3.303762       1       M    33        13.0
476       80  Button_tone      FCz -1.079905       1       M    33        13.0
477       80     Playback      FCz -3.960426       1       M    33        13.0
478       80  Button_tone       Cz -1.675558       1       M    33        13.0
479       80     Playback       Cz -3.792246       1       M    33        13.0
480       81  Button_tone       Fz -1.056308       1       M    56        13.0
481       81     Playback       Fz -1.736073       1       M    56        13.0
482       81  Button_tone      FCz -2.200218       1       M    56        13.0
483       81     Playback      FCz -0.659543       1       M    56        13.0
484       81  Button_tone       Cz -0.936063       1       M    56        13.0
485       81     Playback       Cz -0.147064       1       M    56        13.0

[486 rows x 8 columns]

AttributeError: 'DataFrame' object has no attribute 'group'